### ISSUE TITLE
ALPACA cannot use CONDOR

### ISSUE THREAD

**Issue by rebekka-burkholz** [netZoo/netZooR#103]
When trying to run ALPACA I get the following error message:
Error in create.condor.object(ctrl.elist) : 
  could not find function "create.condor.object"

**Comment by marouenbg** [comment]
Hi @rebekka-burkholz , 
Which ALPCA function do use? Can you share your code?
@twangxxx Could this be an issue of function renaming?

**Comment by rebekka-burkholz** [comment]
Hi Marouen,

I use the function 

library(netZooR)
alpaca(edgelist, folderlocation)

It might be an issue though how I downloaded netZooR.
I had to download 

BiocManager::install("GO.db")
BiocManager::install("org.Hs.eg.db”)

before

devtools::install_github("netZoo/netZooR", build_vignettes = TRUE)

to avoid errors that interrupted the installation of netZooR.

All the best,
Rebekka

**Comment by twangxxx** [comment]
@rebekka-burkholz , is the your `edgelist` variable a 4-column data.frame or table like description below?

A table of edges, with the first column representing the TFs ("from" nodes) and the second column representing the targets ("to" nodes). The third column contains the edge weights corresponding to the control or healthy network, and the fourth column contains the edge weights for the disease network or network of interest.

**Comment by twangxxx** [comment]
@rebekka-burkholz , and also could you share your R version info by run `sessionInfo()` and version of package "GO.db" and "org.Hs.eg.db” by run `packageVersion("GO.db" ) `and `packageVersion("org.Hs.eg.db" )`?

**Comment by rebekka-burkholz** [comment]
@twangxxx, when you look at the code it does not really matter whether it is table or data.frame. It converts it to a dataframe ctrl.elist - and this part works fine.  
Of course, I am happy to share the versions:
R version: 3.6.2 (2019-12-12) 
packageVersion("GO.db"): 3.10.0
packageVersion("org.Hs.eg.db"): 3.10.0

**Comment by marouenbg** [comment]
HI @rburkholz ,
Could you please share the full working example with data and code?
Thanks

**Comment by rebekka-burkholz** [comment]
library(igraph)
library(Matrix)
if (!requireNamespace("BiocManager", quietly = TRUE))
  install.packages("BiocManager")
library(devtools)
devtools::install_github("netZoo/netZooR", build_vignettes = TRUE)
library(netZooR)
g <- sample_bipartite(10, 15, p = 0.4)
ee <- get.edgelist(g)
ee <- cbind(ee, rep(1,dim(ee)[1]), rep(1,dim(ee)[1])) 
alpaca(ee, 'here')

**Comment by marouenbg** [comment]
@rebekka-burkholz This example works for me. It throws an error in the end but it does find the condor function. There is something fonky with your installation.
try
`remove.packages("netZooR")`
Then
```
# install.packages("devtools") 
library(devtools)
# install netZooR pkg with vignettes, otherwise remove the "build_vignettes = TRUE" argument.
devtools::install_github("netZoo/netZooR", build_vignettes = TRUE)
library(netZooR)
```
and try again

**Comment by twangxxx** [comment]
@rebekka-burkholz , I also tried your example, same as Marouen, it can find condor functions. When you re-install netZooR, could you also remove "GO.db", "org.Hs.eg.db" before re-installing netZooR. So for clarify and following up what Marouen suggested, please do below, and let me know this time if Go.db and org.Hs.eg.db can be downloaded automatically along with netZooR.

Try:
```
remove.packages("netZooR")
remove.packages("GO.db")
remove.packages("org.Hs.eg.db")
```

Then:

```
# install.packages("devtools") 
library(devtools)
# install netZooR pkg with vignettes, otherwise remove the "build_vignettes = TRUE" argument.
devtools::install_github("netZoo/netZooR", build_vignettes = TRUE)
library(netZooR)
```

And then try your example:
```
library(igraph)
library(Matrix)
g <- sample_bipartite(10, 15, p = 0.4)
ee <- get.edgelist(g)
ee <- cbind(ee, rep(1,dim(ee)[1]), rep(1,dim(ee)[1]))
# this will throw an error but can return "modularity of projected graph 0.258975026014568" message, suggesting condor can work here.
alpaca(ee, 'here')
```

@marouenbg, when you install netZooR, did it automatically download GO.db, org.Hs.eg.db packages?  Rebekka mentioned she had to download GO.db, org.Hs.eg.db by herself due to interruption during installation, but this didn't happen to me.

**Comment by marouenbg** [comment]
@twangxxx I forgot how I did, but I might have installed Go.db separately.

**Comment by rebekka-burkholz** [comment]
Thanks a lot! After reinstalling Xcode and R, I did not need to download GO.db and org.Hs.eg.db separately. I get a different error now (Error in base::rowSums(x, na.rm = na.rm, dims = dims, ...) : 
  'x' must be numeric). But I assume that is due to bad input from my side that I will investigate.
