### ISSUE TITLE
What's the pipeline for this tool

### ISSUE THREAD

**Issue by echoduan** [netZoo/netZooR#186]
Hello,

     I want to detect the network and target genes relying on the RNA-seq data. I think your tool (netZooR) may be helpful. I have installed it and Cytoscape on my linux platform successfully. But I don't how to utilize your tool relying on the Different expression genes list.

   Could you share the pipeline with me please?

**Comment by marouenbg** [comment]
Hi @echoduan ,

netZooR is package of tools that allow to build networks and analyze them. The tools that allow to reconstruct a network from gene expression are MONSTER, OTTER, PANDA, PUMA. Check the [vignettes](https://netzoo.github.io/netZooR/) in R for the usage as well as [jupyter notebooks](http://netbooks.networkmedicine.org/).

**Comment by echoduan** [comment]
Hi, Thanks for your reply.

     Whether did the files:(ppi_GTEx.txt and motif_GTEx.txt) include all potential genes in human? Can I directly utilize the interaction list in other research in human?

**Comment by marouenbg** [comment]
Yes you can use them in other research, however they don't include all genes. You can increase the coverage bu scanning the genome against TF motif sequence. You can use [CIS-BP](http://cisbp.ccbr.utoronto.ca/) as database for TF motif, the latest human genome sequence [hg38](https://www.ncbi.nlm.nih.gov/assembly/GCF_000001405.26/), and a scanning tool such as [FIMO](http://meme-suite.org/doc/fimo.html). More details can be found [here](https://www.sciencedirect.com/science/article/pii/S2211124720307762)

**Comment by marouenbg** [comment]
Hi @echoduan , closing this for now, please feel free to use [discussions](https://github.com/netZoo/netZooR/discussions) if you have any question!
