### ISSUE TITLE
installation failed for R version 3.4.4

### ISSUE THREAD

**Issue by aconkli4** [netZoo/netZooR#195]
Hi, I am trying install NetZooR. 

Our OS is Ubuntu 18.0.5 LTS

We are using R v3.4.4 (released on 2018/03/15)

When I run devtools::install_github("netZoo/netZooR", build_vignettes = FALSE) I get the following error:

`ERROR: dependency ‘plotrix’ is not available for package ‘STRINGdb’
* removing ‘/home/aconklin/R/x86_64-pc-linux-gnu-library/3.4/STRINGdb’

The downloaded source packages are in
	‘/tmp/RtmpyVhPXb/downloaded_packages’
✔  checking for file ‘/tmp/RtmpyVhPXb/remotes51aa6e1b3241/netZoo-netZooR-7e192ba/DESCRIPTION’ (696ms)
─  preparing ‘netZooR’: (1.8s)
✔  checking DESCRIPTION meta-information
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  looking to see if a ‘data/datalist’ file should be added
─  building ‘netZooR_0.9.tar.gz’
   
Installing package into ‘/home/aconklin/R/x86_64-pc-linux-gnu-library/3.4’
(as ‘lib’ is unspecified)
ERROR: dependency ‘STRINGdb’ is not available for package ‘netZooR’
* removing ‘/home/aconklin/R/x86_64-pc-linux-gnu-library/3.4/netZooR’
Warning messages:
1: package ‘plotrix’ is not available (for R version 3.4.4) 
2: In i.p(...) :
  installation of package ‘STRINGdb’ had non-zero exit status
3: In i.p(...) :
  installation of package ‘/tmp/RtmpyVhPXb/file51aa1375e64b/netZooR_0.9.tar.gz’ had non-zero exit status
`

Will you please look into this for me? I appreciate any help.

Thanks,
Austin

**Comment by marouenbg** [comment]
Hi Austin,

Unfortunately, plotrix requires R3.5 and higher https://cran.r-project.org/web/packages/plotrix/index.html
if you can update R, that would be great. 

Marouen

**Comment by aconkli4** [comment]
Okay, that was my suspicion. Will do!

Thanks,
Austin
