### ISSUE TITLE
CRANE: Error in t.test.default(dist, mu = alp[[2]][i], alternative = "less",

### ISSUE THREAD

**Issue by talkhanz** [netZoo/netZooR#240]
Hey @marouenbg,

I am running the below script:

```
library(netZooR)
input <- read.csv('./crane_input_toy_example.csv')
alp <- alpaca(input,NULL,verbose=F)
res <- alpacaCrane(input,alp,alpha=0.1,beta=0,iteration=30,isParallel=F)
```

but at the alpacaCrane step, I am getting the below error:

```
Error in t.test.default(dist, mu = alp[[2]][i], alternative = "less",  : 
  data are essentially constant
```
The crane_input_toy_example.csv is uploaded here for reference:
[crane_input_toy_example.csv](https://github.com/netZoo/netZooR/files/8101615/crane_input_toy_example.csv)

**Comment by marouenbg** [comment]
This is the final fix https://github.com/netZoo/netZooR/pull/245

**Comment by marouenbg** [comment]
@talkhanz please close this issue if resolved

**Comment by talkhanz** [comment]
I am getting this issue 
Error in sd(df[i, ], rm.na = TRUE) : unused argument (rm.na = TRUE)

**Comment by marouenbg** [comment]
My bad I swapped the argument order. FIxed here https://github.com/netZoo/netZooR/pull/246

**Comment by talkhanz** [comment]
its working

**Comment by marouenbg** [comment]
Closing issue for now but for future reference this is only a workaround and not a final fix.
