### ISSUE TITLE
lionessPy saves file output regardless of 'save_single_network'

### ISSUE THREAD

**Issue by jbeckman1** [netZoo/netZooR#275]
Output from calling lionessPy is always saved to a folder 'lioness_output' regardless of what I enter into 'save_single_network' or 'save_dir'.  I had interpreted setting 'save_single_network' to FALSE as preventing **any** output from being written into my working directory.  Am I misunderstanding the scope of this argument?

**Comment by marouenbg** [comment]
Hi @jbeckman1 ,
Thank you for reporting this issue, I've updated lionessPy code to account for these parameters. Please reinstall netZooR from the `devel` branch and let me know if this works.

**Comment by jbeckman1** [comment]
Hi @marouenbg , thanks for the quick reply.  Unfortunately, I am still seeing a directory named `lioness_output` and the file lioness.npy regardless of those arguments.  This was my test case:

`# refer to the input datasets files of control in inst/extdat as example
control_expression_file_path <- system.file("extdata", "expr10_reduced.txt", package = "netZooR", 
                                            mustWork = TRUE)
motif_file_path <- system.file("extdata", "chip_reduced.txt", package = "netZooR", mustWork = TRUE)
ppi_file_path <- system.file("extdata", "ppi_reduced.txt", package = "netZooR", mustWork = TRUE)

# Run LIONESS algorithm

control_lioness_result <- lionessPy(expr_file = control_expression_file_path, 
                                    save_tmp = FALSE,
                                    motif_file = motif_file_path, 
                                    ppi_file = ppi_file_path, 
                                    modeProcess="union",
                                    start_sample=1, 
                                    end_sample=1, 
                                    precision="single", 
                                    save_single_network = FALSE, 
                                    save_dir = 'test')`

**Comment by marouenbg** [comment]
My bad @jbeckman1, I pushed new code that should fix it https://github.com/netZoo/netZooR/pull/277

Let me know !

**Comment by jbeckman1** [comment]
Works perfectly!  Thank you so much
