### ISSUE TITLE
Got error while running PUMA through netZooR

### ISSUE THREAD

**Issue by kr-swapnil** [netZoo/netZooR#309]
PUMA run Error in seq.default(1, num.TFs * num.TFs, num.TFs + 1) :    wrong sign in 'by' argument. How to solve this?

**Comment by marouenbg** [comment]
Hi @kr-swapnil,
Happy new year! Would you mind sharing a working example I can reproduce?

**Comment by kr-swapnil** [comment]
Input sample files:
1. miRNA-target [sample_miR_target.txt](https://github.com/netZoo/netZooR/files/13816311/sample_miR_target.txt)
2. Gene expression [sample_gexpr.txt](https://github.com/netZoo/netZooR/files/13816313/sample_gexpr.txt)
3. miRNA list [sample_miR_list.txt](https://github.com/netZoo/netZooR/files/13816318/sample_miR_list.txt)

Command:
mir.tar = read.table("sample_miR_target.txt", head=T)
tmp.expr = read.table("sample_gexpr.txt", head=T)
mir.list = read.table("sample_miR_list.txt", head=T)

puma.res = puma(motif = mir.tar, expr = tmp.expr, ppi = NULL, alpha = 0.1, mir_file = mir.list$x, iter = 1000, output = "regulatory", progress = TRUE, randomize = "within.gene", edgelist = TRUE, mode = "intersection")

**Comment by marouenbg** [comment]
Thank you @kr-swapnil! Happy new year to you as well! I am sorry this took too long, if you can work with the MATLAB version https://github.com/netZoo/netZooM/blob/master/netZooM/puma/RunPUMA.m until we get this fixed, otherwise I will get back to you as soon as I can.

**Comment by marouenbg** [comment]
Thanks for your patience @kr-swapnil , the issue has now been fixed in https://github.com/netZoo/netZooR/pull/310
You can reinstall netZooR from the `devel` branch

**Comment by marouenbg** [comment]
Please let me know if you need anything else.
Marouen
