### ISSUE TITLE
Issue Running MONSTER Using netZooR

### ISSUE THREAD

**Issue by wilsonavac** [netZoo/netZooR#311]
.Rmd = copd_smoking_feature_grn.Rmd
line 293

#MONSTER wrapper to input PANDA Results 
domonster <- function(exp_graph, control_graph){
  combdf <- as.data.frame(cbind(control_graph, exp_graph))
  combdes <- c(rep(0, ncol(control_graph)),rep(1, ncol(exp_graph)))
  res <- monster(expr = combdf, 
                                           design = combdes,
                                           motif = NA,
                                           nullPerms = 1,
                                           numMaxCores = 1,
                                           mode = 'regNet')
  return(res)
}

#Inputs
##I checked inputs for Inf, NA, and Nan values and they were not present 
y_cp_grn = read.table("/home/rstudio/copdgene_yes_cp_dev_panda.txt",sep=" ", header=T)
n_cp_grn = read.table("/home/rstudio/copdgene_no_cp_dev_panda.txt",sep=" ", header=T)

#Run MONSTER 
ynmonster = domonster(y_cp_grn, n_cp_grn)

#error 
NAs introduced by coercionError in lm.fit(x, y, offset = offset, singular.ok = singular.ok, ...) : 
  NA/NaN/Inf in 'y'

**Comment by marouenbg** [comment]
Hi @wilsonavac ,

if the input to MONSTER is a GRN, it has to be in TF-by-Gene format, I clarified the docs a bit here https://github.com/netZoo/netZooR/pull/312/files

Marouen
