### ISSUE TITLE
Issue with running MONSTER "monsterPlotMonsterAnalysis" function in R

### ISSUE THREAD

**Issue by wilsonavac** [netZoo/netZooR#313]
`monsterPlotMonsterAnalysis(ynmonster)`

error message:
Error in (function (cond)  : 
  error in evaluating the argument 'x' in selecting a method for function 'mean': subscript out of bounds
Error during wrapup: 'length = 2' in coercion to 'logical(1)'
Error: no more error handlers available (recursive errors?); invoking 'abort' restart

**Comment by marouenbg** [comment]
Hi @wilsonavac ,
Do you have data to reproduce this error?

**Comment by marouenbg** [comment]
@wilsonavac I am closing for ow, feel free to reopen if you have data for me to reproduce the error on my computer.
