### ISSUE TITLE
TIGER in netZooR

### ISSUE THREAD

**Issue by Gaoyuan-Li** [netZoo/netZooR#322]
Hello,

I am trying to use the TIGER function in the netZooR package, but I encountered a few issues:

1. The tiger() function is not available in the Bioconductor release version 1.8.0. Also, it is not in the [Reference Manual](https://www.bioconductor.org/packages/release/bioc/manuals/netZooR/man/netZooR.pdf)

2. The documentation for the tiger() function is blank. https://netzoo.github.io/netZooR/reference/tiger.html

I am currently using the netZooR package version 1.8.0 from Bioconductor. Could you please advise on how and where I can use the tiger() function? Is there an alternative method or a different version of the package where this function is available and documented?

Thank you for your assistance.

Best,
Gaoyuan

**Comment by marouenbg** [comment]
Hi @Gaoyuan-Li cc @cchen22 

1. You can install the newest netZooR version by typing `remotes::install_github("netZoo/netZooR@devel")`
It takes a while for Bioconductor to get the latest updates
2. I working on the docs for TIGER but you can access them here: https://github.com/netZoo/netZooR/blob/master/R/TIGER.R#L22

Thank you,
Marouen

**Comment by marouenbg** [comment]
Fixing TIGER docs https://github.com/netZoo/netZooR/pull/323

**Comment by marouenbg** [comment]
Tiger documentation is now fixed: https://netzoo.github.io/netZooR/reference/tiger.html
